---
name: CommandExploitFix
description: Fixes a command exploit that can be used to bypass certain things, such as a combat cooldown.
version: 1.0
main: ethaniccc\CommandExploitFix\Main
api: 3.17.0
mcpe-protocol:
  - 419
  - 422
...
